/**
 * material.hpp - Material and Node System
 * ========================================
 * 
 * Material properties and Blender's node-based material system:
 * - SocketValue: Value types for node sockets
 * - NodeSocket: Input/output connections
 * - MaterialNode: Single node in shader graph
 * - NodeTree: Complete material node graph
 * - Material: Physical material properties
 * - Hit: Ray-surface intersection result (needs Material)
 */

#pragma once
#include "../math/vec3.hpp"
#include <vector>
#include <string>

// ========== Node Graph Structures ==========

/**
 * SocketValue: Union type for socket values
 * 
 * CRITICAL: Must use correct field for each type!
 * - VEC4 type → use v4 and v4_w fields
 * - VEC3 type → use v3 field  
 * - FLOAT type → use f field
 */
struct SocketValue {
    enum Type { FLOAT, VEC3, VEC4, STRING, BOOL, NONE };
    Type type;
    float f;          // For FLOAT - single scalar value
    Vec3 v3;          // For VEC3 - 3D vector (normals, positions)
    Vec3 v4;          // For VEC4 - RGB component (colors with alpha)
    float v4_w;       // For VEC4 - Alpha component
    std::string s;    // For STRING - texture paths, etc.
    bool b;           // For BOOL - boolean switches
    
    SocketValue() : type(NONE), f(0), v3(), v4(), v4_w(0), b(false) {}
    
    static SocketValue makeFloat(float val) { 
        SocketValue sv; 
        sv.type = FLOAT; 
        sv.f = val; 
        return sv; 
    }
    
    static SocketValue makeVec3(float x, float y, float z) { 
        SocketValue sv; 
        sv.type = VEC3; 
        sv.v3 = Vec3(x, y, z); 
        return sv; 
    }
    
    static SocketValue makeVec4(float x, float y, float z, float w) { 
        SocketValue sv; 
        sv.type = VEC4; 
        sv.v4 = Vec3(x, y, z); 
        sv.v4_w = w; 
        return sv; 
    }
};

/**
 * NodeSocket: Input or output socket on a node
 */
struct NodeSocket {
    std::string name;           // Socket name (e.g., "Base Color", "BSDF")
    std::string type;           // Socket type ("VALUE", "RGBA", "VECTOR", "SHADER")
    SocketValue default_value;  // Default value when not connected
    bool is_linked;             // Is this socket connected to another node?
    std::string linked_node;    // Name of connected node (if is_linked)
    std::string linked_socket;  // Name of connected socket (if is_linked)
    
    NodeSocket() : is_linked(false) {}
};

/**
 * MaterialNode: Single node in material graph
 */
struct MaterialNode {
    std::string name;   // Unique node name (generated by Blender)
    std::string type;   // Node type ("ShaderNodeBsdfPrincipled", "ShaderNodeMix", etc.)
    std::string label;  // User-visible label
    std::vector<NodeSocket> inputs;   // Input sockets
    std::vector<NodeSocket> outputs;  // Output sockets
    
    // Find input socket by name
    const NodeSocket* findInput(const std::string &name) const {
        for(const auto &s : inputs) {
            if(s.name == name) return &s;
        }
        return nullptr;
    }
};

/**
 * NodeTree: Complete material node graph
 */
struct NodeTree {
    std::vector<MaterialNode> nodes;
    bool valid;
    
    NodeTree() : valid(false) {}
    
    // Find node by name
    const MaterialNode* findNode(const std::string &name) const {
        for(const auto &n : nodes) {
            if(n.name == name) return &n;
        }
        return nullptr;
    }
    
    // Find Material Output node (entry point for material evaluation)
    const MaterialNode* findOutputNode() const {
        for(const auto &n : nodes) {
            if(n.type == "ShaderNodeOutputMaterial") return &n;
        }
        return nullptr;
    }
};

// ========== Material Definition ==========

/**
 * Material - Physical material properties
 */
struct Material {
    Vec3 albedo;        // Base color (diffuse reflectance)
    float metallic;     // Metallic factor (0=dielectric, 1=metal)
    float roughness;    // Surface roughness
    Vec3 emission;      // Emission color * strength
    float transmission; // Glass/transparency (0=opaque, 1=fully transparent)
    float ior;          // Index of Refraction
    
    // Node-based material system
    NodeTree nodeTree;  // Full node graph from Blender
    bool useNodes;      // Should we use node tree or legacy properties?
    
    Material() 
        : albedo(0.8f, 0.8f, 0.8f)
        , metallic(0.0f)
        , roughness(0.5f)
        , emission(0.0f, 0.0f, 0.0f)
        , transmission(0.0f)
        , ior(1.45f)
        , useNodes(false) {}
    
    Material(Vec3 a, float m, float r) 
        : albedo(a)
        , metallic(m)
        , roughness(r)
        , emission(0.0f, 0.0f, 0.0f)
        , transmission(0.0f)
        , ior(1.45f)
        , useNodes(false) {}
    
    Material(Vec3 a, float m, float r, Vec3 e) 
        : albedo(a)
        , metallic(m)
        , roughness(r)
        , emission(e)
        , transmission(0.0f)
        , ior(1.45f)
        , useNodes(false) {}
};

// ========== Hit Structure (needs Material) ==========

// Now we can define Hit properly
struct Hit {
    bool hit;
    float t;
    Vec3 point;
    Vec3 normal;
    Vec2 uv;
    bool hasUV;
    Material material;
    int meshIdx;
    int triIdx;
    
    Hit() : hit(false), t(1e30f), hasUV(false), meshIdx(-1), triIdx(-1) {}
};
