/**
 * material.hpp - Material and Node System (Unit-Safe)
 * ====================================================
 * 
 * Material properties and Blender's node-based material system:
 * - SocketValue: Value types for node sockets
 * - NodeSocket: Input/output connections
 * - MaterialNode: Single node in shader graph
 * - NodeTree: Complete material node graph
 * - Material: Physical material properties
 * - Hit: Ray-surface intersection result
 * 
 * Physical Units:
 * - albedo: Color3 (dimensionless reflectance [0,1])
 * - emission: Radiance3 [W/(sr·m²)]
 * - Hit.point: Position3 [m]
 * - Hit.normal: Direction3 (dimensionless)
 * - Hit.t: Distance [m]
 */

#pragma once
#include "../math/vec3_unit.hpp"
#include "../math/vec2.hpp"
#include "../units/units.hpp"
#include <vector>
#include <string>

// ========== Node Graph Structures ==========

/**
 * SocketValue: Union type for socket values
 * 
 * CRITICAL: Must use correct field for each type!
 * - VEC4 type → use v4 and v4_w fields
 * - VEC3 type → use v3 field  
 * - FLOAT type → use f field
 */
struct SocketValue {
    enum Type { FLOAT, VEC3, VEC4, STRING, BOOL, NONE };
    Type type;
    float f;                      // For FLOAT - single scalar value
    diy::Direction3 v3;           // For VEC3 - 3D vector (normals, positions)
    diy::Color3 v4;               // For VEC4 - RGB component (colors with alpha)
    float v4_w;                   // For VEC4 - Alpha component
    std::string s;                // For STRING - texture paths, etc.
    bool b;                       // For BOOL - boolean switches
    
    SocketValue() : type(NONE), f(0), v3(), v4(), v4_w(0), b(false) {}
    
    static SocketValue makeFloat(float val) { 
        SocketValue sv; 
        sv.type = FLOAT; 
        sv.f = val; 
        return sv; 
    }
    
    static SocketValue makeVec3(float x, float y, float z) { 
        SocketValue sv; 
        sv.type = VEC3; 
        sv.v3 = diy::Direction3(x, y, z); 
        return sv; 
    }
    
    static SocketValue makeVec4(float x, float y, float z, float w) { 
        SocketValue sv; 
        sv.type = VEC4; 
        sv.v4 = diy::Color3(x, y, z); 
        sv.v4_w = w; 
        return sv; 
    }
};

/**
 * NodeSocket: Input or output socket on a node
 */
struct NodeSocket {
    std::string name;           // Socket name (e.g., "Base Color", "BSDF")
    std::string type;           // Socket type ("VALUE", "RGBA", "VECTOR", "SHADER")
    SocketValue default_value;  // Default value when not connected
    bool is_linked;             // Is this socket connected to another node?
    std::string linked_node;    // Name of connected node (if is_linked)
    std::string linked_socket;  // Name of connected socket (if is_linked)
    
    NodeSocket() : is_linked(false) {}
};

/**
 * MaterialNode: Single node in material graph
 */
struct MaterialNode {
    std::string name;   // Unique node name (generated by Blender)
    std::string type;   // Node type ("ShaderNodeBsdfPrincipled", "ShaderNodeMix", etc.)
    std::string label;  // User-visible label
    std::vector<NodeSocket> inputs;   // Input sockets
    std::vector<NodeSocket> outputs;  // Output sockets
    
    // Find input socket by name
    const NodeSocket* findInput(const std::string &name) const {
        for(const auto &s : inputs) {
            if(s.name == name) return &s;
        }
        return nullptr;
    }
};

/**
 * NodeTree: Complete material node graph
 */
struct NodeTree {
    std::vector<MaterialNode> nodes;
    bool valid;
    
    NodeTree() : valid(false) {}
    
    // Find node by name
    const MaterialNode* findNode(const std::string &name) const {
        for(const auto &n : nodes) {
            if(n.name == name) return &n;
        }
        return nullptr;
    }
    
    // Find Material Output node (entry point for material evaluation)
    const MaterialNode* findOutputNode() const {
        for(const auto &n : nodes) {
            if(n.type == "ShaderNodeOutputMaterial") return &n;
        }
        return nullptr;
    }
};

// ========== Material Definition ==========

/**
 * Material - Physical material properties for PBR rendering (unit-safe)
 */
struct Material {
    diy::Color3 albedo;         // Base color (dimensionless [0,1])
    float metallic;             // Metallic factor (dimensionless, 0-1)
    float roughness;            // Surface roughness (dimensionless, 0-1)
    diy::Radiance3 emission;    // Emission [W/(sr·m²)]
    float transmission;         // Glass/transparency (dimensionless, 0-1)
    float ior;                  // Index of Refraction (dimensionless)
    
    NodeTree nodeTree;
    bool useNodes;
    
    Material() 
        : albedo(0.8f, 0.8f, 0.8f)
        , metallic(0.0f)
        , roughness(0.5f)
        , emission(0.0f, 0.0f, 0.0f)
        , transmission(0.0f)
        , ior(1.45f)
        , useNodes(false) {}
    
    Material(const diy::Color3& a, float m, float r) 
        : albedo(a), metallic(m), roughness(r)
        , emission(0.0f, 0.0f, 0.0f)
        , transmission(0.0f), ior(1.45f), useNodes(false) {}
    
    Material(const diy::Color3& a, float m, float r, const diy::Radiance3& e) 
        : albedo(a), metallic(m), roughness(r)
        , emission(e)
        , transmission(0.0f), ior(1.45f), useNodes(false) {}
};

// ========== Hit Structure ==========

/**
 * Hit - Ray-surface intersection result (fully typed)
 * 
 * All spatial values use typed units:
 * - t: Distance [m] - ray parameter
 * - point: Position3 [m] - intersection point
 * - normal: Direction3 (dimensionless) - surface normal
 */
struct Hit {
    bool hit;
    diy::units::Distance t;     // Ray parameter [m]
    diy::Position3 point;       // Intersection point [m]
    diy::Direction3 normal;     // Surface normal (normalized)
    Vec2 uv;                    // Texture coordinates (dimensionless)
    bool hasUV;
    Material material;
    int meshIdx;
    int triIdx;
    
    Hit() 
        : hit(false)
        , t(1e30f * mp_units::si::metre)
        , hasUV(false)
        , meshIdx(-1)
        , triIdx(-1) {}
    
    // Type accessors (primary interface)
    diy::units::Distance distance() const { return t; }
    const diy::Position3& position() const { return point; }
    const diy::Direction3& surfaceNormal() const { return normal; }
    
    // Internal geometry access (for intersection calculations)
    float t_meters() const { return diy::units::to_meters(t); }
    float point_x() const { return point.x_raw(); }
    float point_y() const { return point.y_raw(); }
    float point_z() const { return point.z_raw(); }
    float normal_x() const { return normal.x_raw(); }
    float normal_y() const { return normal.y_raw(); }
    float normal_z() const { return normal.z_raw(); }
    
    // Setters for internal use (from geometry code)
    void setFromTyped(diy::units::Distance t_typed, const diy::Position3& p, const diy::Direction3& n) {
        t = t_typed;
        point = p;
        normal = n;
    }
};